<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Cargo;

class CargosSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            'Gerente',
            'Jefe',
            'Supervisor',
            'Técnico Instalador',
            'Ejecutivo Call Center',
            'Administrativo',
            'Ayudante',
            'Ingeniero',
            'Asistente',
            'Despachador',
            'Consultor',
            'Encargado',
            'Maestro',
            'Operador',
            'Vendedor',
            'Chofer',
            'Otro',
            'Montajista',
            'Montajista Soldador',
            'Inspector de Obras',
            'Jefe de Terreno',
            'Ayudante Montajista Soldador',
            'Electrico',
            'Montajista Supervisor',
            'Supervisor Montajista Ito',
            'Ayudante Montajista',
            'Ito Supervisor',
            'Técnico',
            'Ayudante OOCC',
            'Ingeniero Electricista',
            'Gerente de Operaciones',
            'Prevencionista de Riesgos',
            'Ingeniero Civil',
            'Técnico Eléctrico',
            'Jefe de Grupo',
            'Ayudante Técnico',
            'Instalador',
            'Coordinador Proyecto.',
            'Jefe Dpto PPRR.',
            'Guardia de Seguridad',
            'Técnico reparador',
            'Tecnico Multiskill',
            'Técnico MDF',
            'Técnico Localizador',
            'Técnico Linea',
            'Técnico Empalmador',
            'Técnico Autonomo',
            'Técnico de mantencion',
            'Jefe de mantenimiento',
            'Asistente de Operaciones.',
            'Jefe de contrato',
            'Analista ambiental',
            'Asistente Call Center',
            'Supervisor de mantenimiento',
            'Proyectista electrico',
            'Supervisor técnico operaciones.',
            'Analista Senior',
            'MDF-Plantero',
            'Supervisor general planta externa',
            'Supervisor instalaciones',
            'Supervisor logístico',
            'Supervisor MDF',
            'Supervisor zonal',
            'Técnico aprendiz',
            'Técnico de telecomunicaciones',
            'Técnico reparaciones multiprod',
            'Supervisor de campo instala',
            'Supervisor de campo repara',
            'Supervisor de procesos',
            'Técnico multifuciones',
            'Técnico especialista de telecomunicaciones',
            'Jefe de turno',
            'CCTV',
            'supervisor ambiental y alimentario',
            'Conductor vehículo liviano desde 3.500 kg',
            'Operador Maquinaria',
            'Maestro OOCC y Ayudante',
            'Maestro Eléctrico y Ayudante Eléctrico Subterráneo',
            'Maestro Eléctrico y Ayudante Eléctrico.',
            'Capataz y/o Líder de cuadrilla OOCC',
            'Capataz y/o Líder de cuadrilla OOEE',
            'Supervisor OOCC',
            'Supervisor OOEE',
            'Técnico en Instalaciones Multipro',
            'Albañil',
            'Empalmador',
            'Maestro Liniero',
            'Excavador',
            'Supervisor Planta Externa',
            'Técnico Localizador',
            'Técnico Planta Externa',
            'Coordinador OOCC',
            'Técnico Proceso Multiservicio',
            'Técnico Multiskill CU',
            'Ayudante ATC',
            'Higiene y Seguridad',
            'Auditoria de Calidad',
            'Empalmador, Líneas',
            'Planta Interna',
            'Líneas, Canalización',
            'Localización',
            'Emp, Loc, Línea, Diseño, Fib. Óp.',
            'Diseño',
            'Fibra Óptica',
            'Líneas',
            'Técnico en Telecomunicaciones',
            'Tesorero',
            'Supervisora',
            'Cajero',
            'Cajero y Asistente EST',
            'Administrador(a) EST',
            'Asistente de Estacionamiento',
            'Operador Sala Sistema',
            'Asistente y Cajero de Estacionamiento',
            'Valet Parking',
            'Ejecutiva de Ventas',
            'Aseador',
            'Recepcionista',
            'Auditor (a)',
            'Jefe de Tesoreria',
            'Coordinadora de Auditoria',
            'Jefe de Reparaciones',
            'Soldador Mantenedor',
            'Ductero Mantenedor',
            'Asesor Técnico',
            'Jefe de Seguridad',
            'Radioperador',
            'GGSS',
            'Motorista',
            'Sacacolaciones',
            'Supervisor Operativo',
            'Operador CCTV',
            'Supervisor Administrativo',
            'Administrativo(a)',
            'Jefe de Turno',
            'Supervisor Seguridad',
            'Sala de Control',
            'Guardia',
            'Maestro Eléctrico',
            'Capataz',
            'Bodeguero',
            'Mecánico',
            'Ayudante Eléctrico',
            'Chofer Ayudante',
            'Jefe de Operaciones',
            'Maestro Primera',
            'Maestro Segunda',
            'Ayudante Excavador',
            'Ayudante Bodega y Enfierrador',
            'Ayudante de Bodega',
            'Operador Retroexcavadora',
            'Ayudante Albañil',
            'Capataz de Obra',
            'Administrador de Obras',
            'Dibujante Eléctrico',
            'Inspector Supervisores',
            'Maestro de Obras Civiles',
            'Maestro Instalador',
            'Maestro Albañil',
            'Chofer de Camión',
            'Gerente General',
            'Facility Manager',
            'Técnico Climatización',
            'BMS Control Centralizado',
            'Multitécnico Ayudante',
            'Administrativo Facility',
            'Engineering Support',
            'Ayudante de Aseo',
            'Jardinero',
            'Auditor de Calidad ATC',
            'Técnico Junior',
            'DOMICAP 1',
            'DOMICAP 2',
            'DOMICAP 3',
            'Supervisor Terreno ATC',
            'DOMICAP 4',
            'DOMICAP 5',
            'DOMICAP 6',
            'DOMICAP 7',
            'Auditor Planta Externa',
            'Ayudante Empalme de F.O',
            'Localizador',
            'Maestro Empalme Cobre',
            'Maestro Empalme F.O',
            'Proyectista',
            'Supervisor Mantención',
            'Supervisor Creación',
            'Maestro Empalmador',
            'Auxiliar de Aseo',
            'Técnico en Terreno',
            'Supervisor en terreno',
            'Tecnico Multitarea',
            'Maestro Localizador',
            'Maestro Empalmador Fibra',
            'Empalmador fibra óptica',
            'Supervisor Línea Energizada',
            'Maestro Línea Energizada',
            'Ayudante Camión Grúa',
            'Maestro Excavador',
            'Ayudante de Soldador',
            'Cocinero',
            'Patrón de Nave Menor',
            'Secretaria ADM',
            'Ayudante Maestro',
            'Ayudante de Revestimiento',
            'Operador Bomba de Hormigón',
            'Maestro Revestimiento',
            'Operador Camión Aljibe',
            'Soldador',
            'Jefe de Área',
            'Jefe de Cuadrilla',
            'Anfitrión',
            'Mantenimiento de Ascensores y escalas mecánicas',
            'Ayudante de Maestro albañil',
            'Ejecutivo Call',
            'Supervisores',
            'Ejecutivo',
            'Soportes',
            'Coordinador Técnico especialista',
            'Técnico Senior',
            'Analista especialista',
            'Asistente ejecutiva subgerencia',
            'Ingeniero especialista',
            'Jefe área especialista',
            'Supervisor especialista',
            'Técnico en mantenimiento y obras eléctricas',
            'Buzo',
            'Operador DRON',
            'Supervisor de Buceo',
            'Alarife',
            'Vidriero',
            'Supervisor Aseo',
            'conductor',
            'Supervisor Guardia',
            'Operario Polifuncional',
            'Jefe de Obra',
            'Ayudante Carpintero',
            'Ceramista',
            'Jornal',
            'Analista',
            'Digitador',
            'Terapeuta Ocupacional',
            'Limpia Vidrios',
            'Instalador Grafico',
            'Técnico en Mantención',
            'Supervisor Eléctrico',
            'Maestro hojalatero',
            'Electricista',
            'Pintor',
            'Carpintero',
            'Maestro Gasfiter',
            'Técnico en refrigeración y climatización',
            'Técnico Electromecanico',
            'Jefe de Servicios Técnico',
            'Ingeniero en climatización',
            'Encargado Mantención',
            'Ayudante Refrigeración',
            'Personal de Aseo',
            'Ayudante Administrativo',
            'Encargado Aseguramiento de Calidad',
            'Implementador',
            'Operador de Grua',
            'Reponedor',
            'Secretaria de Gerencia',
            'Ejecutivo Servicios Financieros',
            'Operario',
            'Operario Descarga y Pesaje',
            'Operario Consolidador',
            'Ayudante Panificador',
            'Panificador',
            'Supervisor de Panaderia',
            'Supervisor Visita',
            'Jefe Visita',
            'Gerente Visita',
            'APR Visita',
            'Jefe de Panaderia',
            'Sub Jefe Panaderia',
            'Informático',
            'Técnico Informático',
            'Ingeniero Informático',
            'Jefe Informático',
            'Mantenimiento',
            'Técnico Telecomunicacional',
            'Especialista Telefonica',
            'Captador',
        ];

        // Normaliza espacios/duplicados y crea si no existe
        $items = array_values(array_unique(array_map(fn($v) => trim($v), $items)));

        foreach ($items as $nombre) {
            if ($nombre === '') continue;
            Cargo::firstOrCreate(['nombre' => $nombre]);
        }
    }
}
